/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_itcast_ndk4_DataProvider */

#ifndef _Included_cn_itcast_ndk4_DataProvider
#define _Included_cn_itcast_ndk4_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_ndk4_DataProvider
 * Method:    callmethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_ndk4_DataProvider_callmethod1
  (JNIEnv *, jobject);

/*
 * Class:     cn_itcast_ndk4_DataProvider
 * Method:    callmethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_ndk4_DataProvider_callmethod2
  (JNIEnv *, jobject);

/*
 * Class:     cn_itcast_ndk4_DataProvider
 * Method:    callmethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_ndk4_DataProvider_callmethod3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
