/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hong_hellojnidemo_MainActivity */

#ifndef _Included_com_hong_hellojnidemo_MainActivity
#define _Included_com_hong_hellojnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hong_hellojnidemo_MainActivity
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hong_hellojnidemo_MainActivity_helloJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
