/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hong_hellojnidemo_TransportData */

#ifndef _Included_com_hong_hellojnidemo_TransportData
#define _Included_com_hong_hellojnidemo_TransportData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hong_hellojnidemo_TransportData
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hong_hellojnidemo_TransportData_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hong_hellojnidemo_TransportData
 * Method:    sayHelloInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hong_hellojnidemo_TransportData_sayHelloInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hong_hellojnidemo_TransportData
 * Method:    inMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hong_hellojnidemo_TransportData_inMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
