/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hong_hellojnidemo_CcallbackJavaMethod */

#ifndef _Included_com_hong_hellojnidemo_CcallbackJavaMethod
#define _Included_com_hong_hellojnidemo_CcallbackJavaMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hong_hellojnidemo_CcallbackJavaMethod
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hong_hellojnidemo_CcallbackJavaMethod_callMethod1
  (JNIEnv *, jobject);

/*
 * Class:     com_hong_hellojnidemo_CcallbackJavaMethod
 * Method:    callMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hong_hellojnidemo_CcallbackJavaMethod_callMethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_hong_hellojnidemo_CcallbackJavaMethod
 * Method:    callMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hong_hellojnidemo_CcallbackJavaMethod_callMethod3
  (JNIEnv *, jobject);

/*
 * Class:     com_hong_hellojnidemo_CcallbackJavaMethod
 * Method:    callMethod4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hong_hellojnidemo_CcallbackJavaMethod_callMethod4
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
